# # triggers

# on:
#   push: 
#     branches: 
#       -lesson-1
#   pull_request: 
#     branches: 
#       -lesson-1

# # Functions

# jobs: 
# #   build job
#   build:
# # Name of the job
#     name: Build 
      
# # The OS to run the job on
#     runs-on: ubuntu-latest
# # steps
#     steps:
#       name: Checkout Code
#          uses: actions/checkout@v2
#       - name: Install node 18
#          uses: actions/setup-node
#         with:
#           node-version: 18.x
#       - name: Install NPM Dependencies
#         run: npm i
#       - name: Build Project
#          run: npm run build
#       - name: Upload artifact in order to deploy
#          uses: actions/upload-artifact@v2
#         with:
#           name: production-files
#           path: ./build
  
# # deploy job

name: Cypress Tests with Dependency and Artifact Caching

on: push

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: ./build

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./build

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm build
          start: npm start
          browser: chrome
